### ISSUE TITLE
Method names of field of type Array have `List` at the end.

### ISSUE THREAD

**Issue by mohsalship** [infodusha/from-protobuf-object#4]
First of all, many thanks for your work. 

Now, consider the following proto message.

```proto3
message GetUsersRequest {
    repeated string user_ids = 1;
}
```

I used grpc_tools_node_protoc to generated static grpc library. The generated code has `setUserIdsList` as the method to set the value for `user_ids`. However, this library tries to set `setUserIds` and this is causing an issue. 

Let me know if you also see this behavior. In case this needs a fix, I can help.

**Comment by infodusha** [comment]
Hello!
Here i am using `protoc-gen-grpc-web`/`protoc-gen-js` to generate test data.
Therefore I a would like to support `grpc_tools_node_protoc` as well, so what I did:
1) Installed the latest `grpc-tools` - `1.12.4`
2) Generated all the test data with the command `grpc_tools_node_protoc --js_out=import_style=commonjs,binary:$OUT_DIR --grpc_out=$OUT_DIR --plugin=protoc-gen-grpc=../../node_modules/.bin/grpc_tools_node_protoc_plugin $1`
3) Verified all the tests passed


I can assume in your case when you have your object passed to the library you need to provide
`{ userIdsList: [] }` instead of `{ userIds: [] }`. That is so as using `new GetUsersRequest().toObject()` will generate you `{ userIdsList: [] }`

Please try my solution and respond if it didn't help

**Comment by mohsalship** [comment]
That makes sense. And, there would be no way to know if the dev used which tool to generate the data. Thanks!

**Comment by infodusha** [comment]
I mean the code is the same for both the tools
I would imagine if someone also faces with same issue we can check if list method exists and throw a detailed error, that would suggest adding `List` to the key.
